# Generated by Django 3.1.14 on 2024-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCitySightHeatScoreRate',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sight_count', models.BigIntegerField(blank=True, null=True)),
                ('heat_score_9_to_10', models.BigIntegerField(blank=True, null=True)),
                ('heat_score_8_to_9', models.BigIntegerField(blank=True, null=True)),
                ('heat_score_7_to_8', models.BigIntegerField(blank=True, null=True)),
                ('heat_score_6_to_7', models.BigIntegerField(blank=True, null=True)),
                ('heat_score_0_to_6', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_city_sight_heat_score_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsCitySightScoreRate',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sight_count', models.BigIntegerField(blank=True, null=True)),
                ('score_count_4_5_to_5', models.BigIntegerField(blank=True, null=True)),
                ('score_count_4_to_4_5', models.BigIntegerField(blank=True, null=True)),
                ('score_count_3_5_to_4', models.BigIntegerField(blank=True, null=True)),
                ('score_count_3_to_3_5', models.BigIntegerField(blank=True, null=True)),
                ('score_count_0_to_3', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_city_sight_score_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsCityStats',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('heat_score', models.BigIntegerField(blank=True, null=True)),
                ('sight_count', models.BigIntegerField(blank=True, null=True)),
                ('sight_count_5a', models.BigIntegerField(blank=True, null=True)),
                ('sight_count_4a', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_city_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsProvinceStats',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
                ('heat_score', models.BigIntegerField(blank=True, null=True)),
                ('sight_count', models.BigIntegerField(blank=True, null=True)),
                ('sight_count_5a', models.BigIntegerField(blank=True, null=True)),
                ('sight_count_4a', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_province_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsSightAHeatScoreTop10Stats',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('sight_id', models.BigIntegerField()),
                ('sight_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('heat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments_count', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=255, null=True)),
                ('img_list', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ads_sight_a_heat_score_top_10_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsSightCommentScoreRate',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('comment_score_count_5', models.BigIntegerField(blank=True, null=True)),
                ('comment_score_count_4', models.BigIntegerField(blank=True, null=True)),
                ('comment_score_count_3', models.BigIntegerField(blank=True, null=True)),
                ('comment_score_count_2', models.BigIntegerField(blank=True, null=True)),
                ('comment_score_count_1', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_sight_comment_score_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsSightCountStats',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('total_sight_count', models.BigIntegerField(blank=True, null=True)),
                ('total_sight_count_5a', models.BigIntegerField(blank=True, null=True)),
                ('total_sight_count_4a', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_sight_count_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsSightProvinceStats',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
                ('heat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sight_count', models.BigIntegerField(blank=True, null=True)),
                ('sight_count_5a', models.BigIntegerField(blank=True, null=True)),
                ('sight_count_4a', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_sight_province_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsSightScoreTop10Stats',
            fields=[
                ('dt', models.DateField(primary_key=True, serialize=False)),
                ('sight_id', models.BigIntegerField()),
                ('sight_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('heat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments_count', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=255, null=True)),
                ('img_list', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ads_sight_score_top_10_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpiderCommentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('sight_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('score', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spider_commentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('sight_id', models.IntegerField()),
                ('content', models.CharField(default='', max_length=25555)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SightInfo',
            fields=[
                ('sight_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='景点id')),
                ('sight_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('province', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tag_list', models.CharField(blank=True, default='', max_length=2555, null=True)),
                ('detail_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('level', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('heat_score', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('comments_count', models.IntegerField(blank=True, default='', null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('intro', models.TextField(blank=True, default='', null=True)),
                ('opening_time', models.CharField(blank=True, default='', max_length=2555, null=True)),
                ('img_list', models.CharField(blank=True, default='', max_length=2555, null=True)),
                ('cover', models.CharField(blank=True, default='', max_length=2555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
