# Generated by Django 3.1.14 on 2024-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceCity',
            fields=[
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('city_link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'province_city',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SpiderCommentinfo',
        ),
        migrations.AlterModelOptions(
            name='commentinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sightinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
